# Site settings
title: SIAG-LA
email: bindel@cornell.edu
description: > # this means to ignore newlines until "baseurl:"
  Web site of the SIAM Activity Group on Linear Algebra.
baseurl: "/siagla/" # the subpath of your site, e.g. /blog/
url: "http://siags.siam.org" # the base hostname & protocol for your site

#encoding: utf-8
encoding: ASCII-8BIT
timezone: America/New_York

defaults:
 - scope:
     path: "meetings"
     type: "pages"
   values:
     subhead: Conferences
     layout: conference
     nav: conf
 - scope:
     type: "meetings"
   values:
     subhead: Conferences
     layout: conf-info
     nav: conf
 - scope:
     type: "posts"
   values:
     layout: post

collections:
  meetings:
    output: true

# Build settings
markdown: kramdown
