welcome:  In this digest are conference updates and upcoming deadlines. 

announce:

  - title:Preconditioning   2017  conference  in  Vancouver,   Canada -- Travel funding
    content: |
     

      We are happy to  inform participants that  funding (NSF) is now  
      available to support  travel   of  junior   U.S.   participants  
      to   the  preconditioning-2017 conference, July 31-August 2, 2017
      Vancouver, Canada  (see <http://www.cs.ubc.ca/~greif/precon17/>).

      Restrictions apply and  they are as follows: You must  be US permanent
      resident  or citizen, and a  junior researcher (defined as someone who
      received the PhD less than 6 years before the conference) and you must
      have no current funding from NSF.  To apply please send a cover letter
      to <saad@umn.edu>  which certifies that  you are eligible to  receive an
      award according to  the rules stated above.  Include a  recent CV, the
      name of  someone we can contact  for a recommendation letter,  and, if
      you are presenting  a paper or poster, the title  and abstract of your
      presentation.
      
  - title: S3PM-2017 in Berkeley, CA -- Travel funding
    content: |
    
       Travel funding is available for eligible early-career participants of 
       S3PM-2017: the International Convention on Shape, Solid, Structure, and 
       Physical Modeling, June 19-23, Berkeley, CA, USA: [s3pm.icsi.berkeley.edu](https://s3pm.icsi.berkeley.edu/). 
       
      The NSF has provided generous funding (final processing approved) to support 
      registration and travel for a number of students enrolled in US educational 
      institutions (including domestic and international student); or US persons 
      (i.e., citizens of lawful permanent residents) who are graduate students in 
      universities outside of the US. Applications from women and under-represented 
      minorities are particularly encouraged. Click [here](https://goo.gl/5lZHy9) to apply now!
     
       
meetings:
  - 2018-05-04-ala

jobs:
  - 2017-04-26-ral