welcome: In the digest this month are annoucements of upcoming conferences and job opportunities. 

announce:

  - title: fill
    content: | 
      fill
      
meetings:
  - 2018-03-07-pp18

jobs:
 - 2017-08-16-ral