welcome: 
announce:

  - title: SIAG/LA Business Meeting Minutes
    content: |
      The minutes from the SIAG/LA Business Meeting, which was held at the SIAM ALA meeting in Hong Kong, are now available from the website.
       


meetings:
 - 2018-08-13-dimacs
 - 2018-08-15-mopta
 - 2019-06-10-ieee
 
jobs:
- 2018-04-12-strathclyde